WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SYSTEM SET db_recovery_file_dest_size = 10G SCOPE=BOTH;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata' SCOPE=BOTH;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER C##DBZUSER IDENTIFIED BY dbz_password CONTAINER=ALL;
GRANT CREATE SESSION TO C##DBZUSER CONTAINER=ALL;
GRANT SET CONTAINER TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##DBZUSER CONTAINER=ALL;
GRANT LOGMINING TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$MYSTAT TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$STATNAME TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON ALL_INDEXES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON ALL_OBJECTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON ALL_TABLES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON ALL_TAB_COLUMNS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON ALL_USERS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_ROLE_PRIVS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_OBJECTS TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_TABLES TO C##DBZUSER CONTAINER=ALL;
GRANT SELECT ON DBA_TAB_COLUMNS TO C##DBZUSER CONTAINER=ALL;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER BANKING IDENTIFIED BY banking_pwd;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO BANKING;
GRANT UNLIMITED TABLESPACE TO BANKING;

ALTER SESSION SET CURRENT_SCHEMA = BANKING;

CREATE TABLE EOD_BALANCE (
    ACCOUNT_ID        VARCHAR2(34) PRIMARY KEY,
    BALANCE_DATE      DATE NOT NULL,
    EOD_AMOUNT        NUMBER(18,2) NOT NULL,
    CURRENCY          VARCHAR2(3) DEFAULT 'EUR' NOT NULL,
    LAST_UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE BOOKINGS (
    BOOKING_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID        VARCHAR2(34) NOT NULL,
    BOOKING_DATE      DATE NOT NULL,
    AMOUNT            NUMBER(18,2) NOT NULL,
    CURRENCY          VARCHAR2(3) DEFAULT 'EUR' NOT NULL,
    OPERATOR          VARCHAR2(50),
    DESCRIPTION       VARCHAR2(255)
);

CREATE INDEX IDX_BOOKINGS_ACCOUNT_DATE ON BOOKINGS (ACCOUNT_ID, BOOKING_DATE);

CREATE TABLE OPERATOR_LOG (
    LOG_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATOR          VARCHAR2(50) NOT NULL,
    ACTION            VARCHAR2(120) NOT NULL,
    ACTION_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DETAILS           VARCHAR2(500)
);

ALTER TABLE EOD_BALANCE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE BOOKINGS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE OPERATOR_LOG ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO EOD_BALANCE (ACCOUNT_ID, BALANCE_DATE, EOD_AMOUNT, CURRENCY)
VALUES ('BA391860123456789012', TRUNC(SYSDATE), 5000.00, 'EUR');

COMMIT;
